### ISSUE TITLE
 uglifyjs压缩js后， json文件里的usingComponents没有生成

### ISSUE THREAD

**Issue by billyshen26** [jardenliu/wepy-plugin-iview#11]
"wepy-plugin-iview": "^1.2.0-rc.2",
    "wepy-plugin-uglifyjs": "^1.3.7"

当我使用uglifyjs压缩js后， 生成的dist文件夹中的page里面的json文件没有usingComponents，到时组件无法使用。以下是uglifyjs配置
  // 压缩js 
  module.exports.plugins = {
    uglifyjs: {
      filter: /\.js$/,
      config: {
      }
    }
  }

请问如何解决

**Comment by jardenliu** [comment]
你的plugin被覆盖了啊

**Comment by billyshen26** [comment]
不好意思，确实被覆盖了，多谢指点

**Comment by encorehe** [comment]
你好 我也碰到这个问题 该如何配置呢？🙏

**Comment by jardenliu** [comment]
if (prod)里面改

**Comment by encorehe** [comment]
怎么改啊 ，找半天了 ，帮忙指教一下呗，🙏

**Comment by jardenliu** [comment]
@encorehe module.exports.plugins ={...} 这里看不出来问题吗？
