### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by xiangwan** [jardenliu/wepy-plugin-iview#2]
https://github.com/jardenliu/wepy-plugin-iview/blob/2d4313f5df1dee7bdaa3b4ef2dbfc9826f794ec3/src/index.js#L107  
 
写死'../'会导致不支持多级目录

**Comment by jardenliu** [comment]
晚些时候，改进一下

**Comment by jardenliu** [comment]
问题已修正

**Comment by jardenliu** [comment]
fixed
