### ISSUE TITLE
没有生效

### ISSUE THREAD

**Issue by woodccc** [jardenliu/wepy-plugin-iview#6]
按照readme 用法来，并没有生效呢。看其他 issue 说的现在不用 install ivew 了吗？我确定安装的是最新版1.1.2。但是不生效。

还有个问题，只看到需要在wepy.config.js中配置 plugin。但是没看到在哪里用了 wepy-plugin-iview  呢？

期待您的回复，谢谢。

**Comment by jardenliu** [comment]
1. 先确认编译，无报错。
2. 查看dist/pages/任意一个json中的usingComponents是否有注入。
3. 需要安装iview-weapp和wepy-plugin-iview
4. wepy的插件调用原理，请查看相关官方文档

**Comment by woodccc** [comment]
@jardenliu j 谢谢，已解决。应该是编译的问题，重新 build 一下就好了。十分感谢。
