### ISSUE TITLE
windows 下问题

### ISSUE THREAD

**Issue by deng-yc** [jardenliu/wepy-plugin-iview#8]
![image](https://user-images.githubusercontent.com/12589538/44890779-85c18600-ad0e-11e8-9042-35d6e667080f.png)
当pages下面的目录不止一层的时候会出现分隔符错误,导致无法解析

**Comment by jardenliu** [comment]
😔万恶的windows

**Comment by jardenliu** [comment]
稍后修正后会更新

**Comment by jardenliu** [comment]
@deng-yc 已经修正，请更新版本
