### ISSUE TITLE
无法使用交互组件

### ISSUE THREAD

**Issue by rongrongt** [jardenliu/wepy-plugin-iview#9]
框架是用wepy,wepy.config配置是按照默认的全局引入iview的组件：`plugins: {
    iview: {
    }
  },`能引入button一些基本组件，但是像model，drawer等交互组件引入后没有生效，页面没有将他们渲染

**Comment by jardenliu** [comment]
![image](https://user-images.githubusercontent.com/15191056/45133578-92d7ec80-b1c8-11e8-9f9f-e1e1446e1893.png)
可以啊

**Comment by jardenliu** [comment]
请根据iview官方文档使用iview的控件，并确认没有报错

**Comment by jardenliu** [comment]
![image](https://user-images.githubusercontent.com/15191056/45133749-7ab49d00-b1c9-11e8-82bf-9406325db0bc.png)
抽屉也可以啊

**Comment by jixieshi999** [comment]
我的也不行，连button样式都没有效果，large normal都一样的

**Comment by jardenliu** [comment]
@rongrongt @jixieshi999 贴上版本号，操作系统，wepy版本号等信息

**Comment by rongrongt** [comment]
我的无法使用的问题已经好了，是我这边的问题，但是又有一个问题，我现在是全局引入的ivew，本地开发的时候是ok的，但是build出来后，发现找不到iview组件，试了一下在需要使用iview组件的文件内单个引入组件，并且一定要使用../../这样的相对路径引用使用是ok的。但不能使用wepy里以@开头的绝对路径引入，不然build后也会找不到。

**Comment by rongrongt** [comment]
"iview-weapp": "^2.0.0",
  "wepy": "^1.6.0",我的是mac最新系统，我同事是win7，我和他都有全局引入时build后找不到文件的问题

**Comment by jardenliu** [comment]
@rongrongt 第一个问题，build出来没有。你没发现`wepy.config.js`下面那句`if (prod)`  plugin被覆盖了吗？
第二个问题，引用原生组件的时候，是不能使用@的啊。

@jixieshi999 请确保`wepy-plugin-iview`版本是最新的`1.2.0-rc.2`
